### PR TITLE
Removed tabs, added network option in config for SuperMUC

### PR DESCRIPTION
**Pull request by saumiJ**

### CODE REVIEW

**Comment by uekerman** [comment]
thanks for cleaning up the tabs!
network="lo", however, is only an option for sockets communication. can you please remove that option from the `mpi-single`?

**Comment by saumiJ** [comment]
Damn, should've checked that. Will do so!

**Comment by uekerman** [comment]
no worries, but i also guess that preCICE does not even allow for that option.
actually, you need `network="ib0"` on supermuc, not `lo`
just to clarify a bit: `lo` is the local network, so sockets are only unique inside one node. if you want to do a socket communication over multiple nodes, you need the infiniband `ib0`

**Comment by saumiJ** [comment]
I've assumed that the user is likely to not be on SuperMUC, so I've left it as the default option `network=lo` in the config file. In a comment beside that, I've indicated that it should be changed to `ib0` on SuperMUC. This has also been mentioned in the Wiki.

I've removed the network option from the `master` tag (since preCICE does not allow that for `mpi` and `mpi-single`).

**Pull request merged**
