### PR TITLE
Update for preCICE v2 and precice/python-bindings

### PR DESCRIPTION
**Pull request by MakisH**
We now have `develop` as default branch, but we should not forget to also merge to `master` from time to time. Now we have a good reason to do so.

See the [migration guide](https://github.com/precice/precice/wiki/Porting-adapters-from-preCICE-1.x-to-2.x).

Reviewer: Check file changes and merge.

### CODE REVIEW

**Comment by MakisH** [comment]
@BenjaminRueth also: why are we now not importing MPI explicitly? Can we now skip it always?

**Comment by BenjaminRodenberg** [comment]
> 
> 
> @BenjaminRueth also: why are we now not importing MPI explicitly? Can we now skip it always?

`from mpi4py import MPI` happens [here](https://github.com/precice/python-bindings/blob/bef71c6d95c1a26ea17371dda533763d1f23b726/precice.pxd#L10). To avoid errors like described in https://github.com/precice/python-bindings/issues/8, this should be sufficient.

**Review by BenjaminRodenberg — APPROVED** [review]
In a testrun I realized that we need two more dependencies. See #32. Everything else looks good.

**Comment by MakisH** [comment]
> > @BenjaminRueth also: why are we now not importing MPI explicitly? Can we now skip it always?
> 
> `from mpi4py import MPI` happens [here](https://github.com/precice/python-bindings/blob/bef71c6d95c1a26ea17371dda533763d1f23b726/precice.pxd#L10). To avoid errors like described in [precice/python-bindings#8](https://github.com/precice/python-bindings/issues/8), this should be sufficient.

I am confused: does this also work if one does not want to use MPI at all?  [precice/python-bindings#8](https://github.com/precice/python-bindings/issues/8) seems to be still open.

I probably am missing some decision history, but I thought we wanted to keep MPI optional.

**Pull request merged**
